### ISSUE TITLE
new_proj() questions feedback/debate

### ISSUE THREAD

**Issue by jzadra** [IntegralEnvision/integral#10]
I'd suggest we not ask to create new file.  First, it doesn't distinguish between R/Rmd, and second, we want people to get used to using the function for a new file.

We could instead put out a message reminding them how to start a new file.

**Comment by ebenp** [comment]
I'm not quite sure what is meant by this. Are you saying that new_proj() should automatically create a new R file without asking? 
Are you thinking new_proj() just creates the project scaffolding and then new_file needs to be run? 
Let's talk about this on Monday's call.

**Comment by ebenp** [comment]
Closed by splitting the file creation from the projection creation in 0a8bf255f34506e730527abf3dcf601ea8388333
