### ISSUE TITLE
new_proj() - output function call with arguments after interactive entry

### ISSUE THREAD

**Issue by jzadra** [IntegralEnvision/integral#12]
This will let people copy paste for next time they run it.  Consider that we need to not include things like the path, just hte things that are preferences.

**Comment by ebenp** [comment]
Is the output a named list?

**Comment by jzadra** [comment]
I was thinking just a message like "If you want to do this using code next time, copy the following: `new_proj(all the arguments based on user entries)`

**Comment by ebenp** [comment]
Ah. That sounds great.

Eben


Eben Pendleton (he/him/his) | Project Scientist
Tel: 207.800.3808
45 Exchange Street, Suite 200 | Portland | ME 04101
***@***.*** | www.integral-corp.com

[cid:integral-logo_bb8ba854-3124-462b-8a66-06670ee4325c.jpg]

**Comment by ebenp** [comment]
Closed with 48e5d70de177467ffb5fbf349dc6ba0149411709
