### ISSUE TITLE
Add on_citrix function

### ISSUE THREAD

**Issue by ebenp** [IntegralEnvision/integral#13]
Create function to detect if on Citrix.
Possible syntax is to find the nodename and see if it starts with APP
grepl("^APP", Sys.info()[[grep("nodename", names(Sys.info()))]])

**Comment by jzadra** [comment]
I'm partial to still using tidyverse rather than base R in functions for the sake of readability... Here's my suggestion. The cli alert in `is_citrix()` is maybe not necessary, but the standalone `current_r_location()` function might be useful at some point too (could use a better name though).
```
is_citrix <- function() {
  x <- Sys.info()["nodename"]
  
  cli::cli_alert_info("R appears to be running on: {current_r_location()}")
  
  stringr::str_detect(x, "APP\\d+")
}

current_r_location <- function() {
  x <- Sys.info()["nodename"]
  
  if(stringr::str_detect(x, "APP\\d+")) return("shitrix") else
    if(stringr::str_detect(x, "rstudio")) return("linux") else
      return("local")
  
}

```

**Comment by ebenp** [comment]
Tidyverse is fine. I'm thinking we probably want a TRUE / FALSE from is_citrix. I think the APP name would be useful though. Maybe FALSE or the APP name?

Eben

Eben Pendleton (he/him/his) | Project Scientist
Tel: 207.800.3808
45 Exchange Street, Suite 200 | Portland | ME 04101
***@***.*** | www.integral-corp.com

[cid:integral-logo_bb8ba854-3124-462b-8a66-06670ee4325c.jpg]

**Comment by jzadra** [comment]
is_citrix() returns a logical.
