### ISSUE TITLE
qa() not capturing all subsections, only qa tags

### ISSUE THREAD

**Issue by kheal** [IntegralEnvision/integral#37]
see this qa sheet: "CF1144_Evraz\Working_Files\Task 0502 Allocation Support\Ash_Grove\ash_grove_analysis\QA\QA_ash_grove_analysis.xlsx" associated with this script: "\\pfs1w\CF1100-CF3999\CF1144_Evraz\Working_Files\Task 0502 Allocation Support\Ash_Grove\ash_grove_analysis\01_data_fetch.R"

**Comment by jzadra** [comment]
Check with 01_data_fetch.R

**Comment by kheal** [comment]
fixed with v0.0.5
