### ISSUE TITLE
Error: HTTP Error 404 on install

### ISSUE THREAD

**Issue by ebenp** [IntegralEnvision/integral#6]
@jzadra  was seeing the below using remotes::install()

![image](https://user-images.githubusercontent.com/4080051/166523089-e1709512-687c-4a39-8de1-da07b0094405.png)

**Comment by ebenp** [comment]
I haven't been able to replicate this. Yet!

**Comment by jzadra** [comment]
This is because I was trying to install (as a user) `integral-private` when I already had `integral` installed.  No further followup needed.
