### ISSUE TITLE
cheat() doesn't find cheat sheets :(

### ISSUE THREAD

**Issue by kheal** [IntegralEnvision/integral#67]
integral::cheat() isn't working to find the cheat sheets as expected.  

Package was freshly re-installed at v# ‘1.0.1.9000’.

![image](https://user-images.githubusercontent.com/10502759/202049924-c14e76a8-8675-4c3f-8f63-d9cd411c7ac9.png)

**Comment by kheal** [comment]
Now it's broken on mac, need to test on both systems before fixing.

**Comment by jzadra** [comment]
This has been resolved
