### ISSUE TITLE
ic_qa() AVD producing strange file paths 

### ISSUE THREAD

**Issue by jzadra** [IntegralEnvision/integral#77]
![image](https://user-images.githubusercontent.com/25590353/218219406-ba157c93-9ea2-46ad-876f-a592181b83ed.png)

**Comment by kheal** [comment]
@jzadra does this stop the functioning of ic_qa() only when not in a project?  My understanding is those file paths are correct and that the integral-data is somehow a map of that location.  ic_qa seems to be working fine inside a project with those file paths.

**Comment by jzadra** [comment]
I wasn't aware of these paths, so if they are working I won't bother with it.  I think though that there may be a place where the script checks for existing files using the \\integral path. I will double check.

**Comment by jzadra** [comment]
Resolved.
